// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbRJM4Y-riA5tbO0HZEGBmuYjuEcPZgpQ',
    appId: '1:481023956338:web:8a58ce6176c937feabf9eb',
    messagingSenderId: '481023956338',
    projectId: 'chat-app-kanagaraj',
    authDomain: 'chat-app-kanagaraj.firebaseapp.com',
    storageBucket: 'chat-app-kanagaraj.appspot.com',
    measurementId: 'G-LPV042WRHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzq0KJpEEiQEdXykW_iIpp3KlAoYjiHA8',
    appId: '1:481023956338:android:166bd810ab059723abf9eb',
    messagingSenderId: '481023956338',
    projectId: 'chat-app-kanagaraj',
    storageBucket: 'chat-app-kanagaraj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF0M5DXyztwete3cAfzWKtaKyFfkz-kfY',
    appId: '1:481023956338:ios:dc58269fd5ac3028abf9eb',
    messagingSenderId: '481023956338',
    projectId: 'chat-app-kanagaraj',
    storageBucket: 'chat-app-kanagaraj.appspot.com',
    iosClientId: '481023956338-k7nj1oa98r0i4g48qq9rmtqmojdhlikl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
